function tpText(id){return (document.getElementById(id)?.value||'').trim();}
function tpNum(id){return Number(tpText(id))||0;}
function tpMoney(n){return '$'+(Number(n)||0).toFixed(2);}
function tpSet(html){document.getElementById('result').innerHTML=html;}
function tpEsc(s){return String(s||'').replace(/[&<>"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c];});}
function tpList(items){return '<ol>'+items.map(function(i){return '<li>'+tpEsc(i)+'</li>';}).join('')+'</ol>';}
function tpCopyResult(){var r=document.getElementById('result'); if(!r)return; navigator.clipboard.writeText(r.innerText||r.textContent||'');}
function tpFiverrTitle(){var s=tpText('service'), n=tpText('niche'), b=tpText('buyer'), tone=tpText('tone'); tpSet('<h3>Gig title ideas</h3>'+tpList(['I will '+s+' for '+b,'I will create professional '+s+' for '+n,'I will help '+b+' with '+s,'I will deliver '+tone.toLowerCase()+' '+s+' for '+n,'I will write, design or optimize '+s+' for your business']));}
function tpFiverrDescription(){var service=tpText('service'), audience=tpText('audience'), deliverables=tpText('deliverables'), exp=tpText('experience'); tpSet('<h3>Gig description draft</h3><pre>Hi, I can help '+audience+' with '+service+'.\n\nWhat you get:\n- '+deliverables.replace(/\n/g,'\n- ')+'\n\nWhy work with me:\n- '+exp+'\n- Clear communication\n- Work prepared according to your instructions\n\nSend me a message before ordering so we can confirm the scope, timeline and required details.</pre>');}
function tpUpworkProposal(){var job=tpText('job'), skill=tpText('skill'), proof=tpText('proof'), q=tpText('question'); tpSet('<h3>Proposal draft</h3><pre>Hello,\n\nI read your job post and understand that you need help with: '+job+'\n\nI can help with '+skill+' by focusing on clear requirements, practical delivery and clean communication. '+proof+'\n\nMy approach would be:\n1. Confirm your goal and examples\n2. Prepare the first draft or work plan\n3. Share the work for review\n4. Apply reasonable revisions based on your feedback\n\nQuick question: '+q+'\n\nThanks,\n[Your Name]</pre>');}
function tpClientEmail(){var type=tpText('emailType'), name=tpText('clientName'), project=tpText('project'), details=tpText('details'); var body='Hi '+name+',\n\n'; if(type==='Project delivery') body+='I have completed the '+project+' and I am sharing it for your review. '+details; else if(type==='Revision response') body+='Thanks for your feedback on '+project+'. I will review the requested changes and update the work according to the agreed scope. '+details; else if(type==='Price negotiation') body+='Thank you for discussing '+project+'. Based on the scope, the price reflects the time, quality checks and revisions needed. '+details; else if(type==='Late payment reminder') body+='I hope you are well. This is a polite reminder about the pending payment for '+project+'. '+details; else body+='I wanted to follow up on '+project+'. '+details; tpSet('<h3>Email draft</h3><pre>'+tpEsc(body+'\n\nBest regards,\n[Your Name]')+'</pre>');}
function tpHourlyRate(){var goal=tpNum('incomeGoal'), expenses=tpNum('expenses'), days=tpNum('days'), hours=tpNum('hours'), buffer=tpNum('buffer'); var total=(goal+expenses)*(1+buffer/100); var billable=days*hours; var rate=billable?total/billable:0; tpSet('<h3>Estimated hourly rate</h3><p><strong>'+tpMoney(rate)+'/hour</strong></p><small>Formula: (income goal + expenses + buffer) / billable hours. This is an estimate, not a guarantee of client acceptance.</small>');}
function tpProjectPrice(){var h=tpNum('projectHours'), r=tpNum('hourlyRate'), rev=tpNum('revisionBuffer'), fee=tpNum('platformFee'); var base=h*r; var buffered=base*(1+rev/100); var gross=fee>=100?buffered:buffered/(1-fee/100); tpSet('<h3>Estimated project price</h3><p>Base: <strong>'+tpMoney(base)+'</strong></p><p>With buffer: <strong>'+tpMoney(buffered)+'</strong></p><p>Suggested price including fee: <strong>'+tpMoney(gross)+'</strong></p>');}
function tpInvoice(){var f=tpText('freelancer'), c=tpText('client'), s=tpText('invoiceService'), a=tpNum('invoiceAmount'), tax=tpNum('tax'), no=tpText('invoiceNo'); var taxAmount=a*tax/100; tpSet('<h3>Invoice preview</h3><p><strong>'+tpEsc(no)+'</strong></p><p>From: '+tpEsc(f)+'<br>To: '+tpEsc(c)+'</p><p>Service: '+tpEsc(s)+'</p><p>Subtotal: '+tpMoney(a)+'<br>Tax: '+tpMoney(taxAmount)+'<br><strong>Total: '+tpMoney(a+taxAmount)+'</strong></p>');}
function tpPaypalFee(){var a=tpNum('amount'), p=tpNum('feePercent'), fixed=tpNum('fixedFee'); var fee=a*p/100+fixed; var receive=a-fee; var request=(a+fixed)/(1-p/100); tpSet('<h3>Fee estimate</h3><p>Fee: <strong>'+tpMoney(fee)+'</strong></p><p>You receive: <strong>'+tpMoney(receive)+'</strong></p><p>To receive '+tpMoney(a)+', request about <strong>'+tpMoney(request)+'</strong>.</p><small>Fees vary by country, account type and currency. Enter the rates shown in your payment account.</small>');}
function tpAffiliateCommission(){var price=tpNum('productPrice'), rate=tpNum('commissionRate'), sales=tpNum('sales'); var per=price*rate/100; tpSet('<h3>Commission estimate</h3><p>Commission per sale: <strong>'+tpMoney(per)+'</strong></p><p>Total for '+sales+' sales: <strong>'+tpMoney(per*sales)+'</strong></p>');}
function tpYoutubeRpm(){var views=tpNum('views'), rpm=tpNum('rpm'); var rev=views/1000*rpm; tpSet('<h3>Revenue estimate</h3><p><strong>'+tpMoney(rev)+'</strong></p><small>Formula: views / 1000 x RPM. Actual YouTube revenue depends on geography, niche, ads, retention and policies.</small>');}
