
(()=>{'use strict';const $=id=>document.getElementById(id);const num=id=>Number($(id)?.value||0);const money=n=>new Intl.NumberFormat(undefined,{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(Number.isFinite(n)?n:0);const days=(a,b)=>Math.max(0,Math.ceil((b-a)/86400000));const weekdays=(a,b,include=true)=>{let n=0,d=new Date(a);d.setHours(12,0,0,0);const end=new Date(b);end.setHours(12,0,0,0);if(!include)d.setDate(d.getDate()+1);while(d<=end){if(d.getDay()!==0&&d.getDay()!==6)n++;d.setDate(d.getDate()+1)}return n};let salaryTimer,meetingTimer,homeTimer;
function salaryRate(annual,daysPerYear,hours){return annual/Math.max(1,daysPerYear)/Math.max(1,hours)}function ticker(target,rate,start){target.textContent=money(((Date.now()-start)/3600000)*rate)}
function result(id,html){const el=$(id);if(el)el.innerHTML=html}function bind(action,fn){document.querySelectorAll('[data-action="'+action+'"]').forEach(b=>b.addEventListener('click',fn))}
bind('home-start',()=>{clearInterval(homeTimer);const rate=salaryRate(num('homeSalary'),260,num('homeHours'));const start=Date.now();$('homeRate').textContent=money(rate)+' per hour';ticker($('homeLive'),rate,start);homeTimer=setInterval(()=>ticker($('homeLive'),rate,start),80)});bind('home-reset',()=>{clearInterval(homeTimer);$('homeLive').textContent='$0.00'});
bind('salary-start',()=>{clearInterval(salaryTimer);const rate=salaryRate(num('annualSalary'),num('workDays'),num('hoursDay'));$('salaryHour').textContent=money(rate);$('salaryDay').textContent=money(rate*num('hoursDay'));$('salarySecond').textContent=money(rate/3600);const start=Date.now();salaryTimer=setInterval(()=>ticker($('salaryLive'),rate,start),80)});bind('salary-reset',()=>{clearInterval(salaryTimer);$('salaryLive').textContent='$0.00'});
bind('payday',()=>{const now=new Date(),end=new Date($('payDate').value+'T12:00:00');if(!end.getTime()||end<now)return result('paydayResult','Choose a future payday.');const d=days(now,end),wd=weekdays(now,end,false);result('paydayResult','<span class="big">'+d+' days</span><span class="accent">'+wd+' weekdays</span> and '+d+' sleeps until payday.');});
bind('workdays',()=>{const now=new Date(),end=new Date($('deadline').value+'T12:00:00');if(!end.getTime()||end<now)return result('workdaysResult','Choose a future deadline.');const wd=weekdays(now,end,$('includeToday').checked);result('workdaysResult','<span class="big">'+wd+' workdays</span><span class="accent">'+days(now,end)+' calendar days</span> until '+end.toLocaleDateString(undefined,{dateStyle:'long'})+'.');});
bind('afford',()=>{const price=num('itemPrice'),rate=num('takeHomePay'),h=Math.max(1,num('dailyHours'));if(price<=0||rate<=0)return result('affordResult','Enter a positive price and hourly pay.');const hours=price/rate,workdays=hours/h;result('affordResult','<span class="big">'+hours.toFixed(1)+' work hours</span>That is <span class="accent">'+workdays.toFixed(1)+' workdays</span> of your life at '+money(rate)+'/hour.');});
bind('subscription',()=>{const monthly=num('monthlyCost'),years=num('subscriptionYears'),rate=num('subHourlyPay');if(monthly<=0||years<=0||rate<=0)return result('subscriptionResult','Enter positive values.');const total=monthly*12*years,hours=total/rate;result('subscriptionResult','<span class="big">'+money(total)+'</span>Over '+years+' years, this costs <span class="accent">'+hours.toFixed(1)+' work hours</span>, or '+(hours/8).toFixed(1)+' eight-hour workdays.');});
bind('commute',()=>{const minutes=num('commuteMinutes'),daysWeek=num('commuteDays'),weeks=num('commuteWeeks'),cash=num('commuteCash'),pay=num('commutePay');const hours=minutes*daysWeek*weeks/60,totalCash=cash*daysWeek*weeks,time=hours*pay,total=totalCash+time;result('commuteResult','<span class="big">'+money(total)+' / year</span><span class="accent">'+hours.toFixed(0)+' hours</span> in transit plus '+money(totalCash)+' out of pocket. That is '+(hours/8).toFixed(1)+' eight-hour days of time.');});
bind('deadline',()=>{const fee=num('projectFee'),hours=num('projectHours'),off=num('projectDaysOff'),now=new Date(),end=new Date($('projectDeadline').value+'T12:00:00');let wd=weekdays(now,end,true)-off;if(!end.getTime()||wd<=0)return result('deadlineResult','Choose a deadline with at least one available weekday.');result('deadlineResult','<span class="big">'+(hours/wd).toFixed(1)+' hours / day</span>Across '+wd+' available workdays, target <span class="accent">'+money(fee/wd)+' revenue per day</span>. Effective project rate: '+money(fee/Math.max(1,hours))+'/hour.');});
bind('meeting-start',()=>{clearInterval(meetingTimer);const annual=num('averageSalary')*(1+num('overhead')/100),rate=annual/2080*num('attendees');$('meetingHour').textContent=money(rate);$('meetingMinute').textContent=money(rate/60);const start=Date.now();meetingTimer=setInterval(()=>ticker($('meetingLive'),rate,start),80)});bind('meeting-reset',()=>{clearInterval(meetingTimer);$('meetingLive').textContent='$0.00'});
const menu=document.querySelector('.mc-menu'),nav=document.querySelector('.mc-nav nav');menu?.addEventListener('click',()=>{nav.style.display=nav.style.display==='flex'?'none':'flex'});
})();
