
(()=>{'use strict';const $=id=>document.getElementById(id);const num=id=>Number($(id)?.value||0);const money=n=>new Intl.NumberFormat(undefined,{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(Number.isFinite(n)?n:0);const days=(a,b)=>Math.max(0,Math.ceil((b-a)/86400000));const weekdays=(a,b,include=true)=>{let n=0,d=new Date(a);d.setHours(12,0,0,0);const end=new Date(b);end.setHours(12,0,0,0);if(!include)d.setDate(d.getDate()+1);while(d<=end){if(d.getDay()!==0&&d.getDay()!==6)n++;d.setDate(d.getDate()+1)}return n};let salaryTimer,meetingTimer,homeTimer;
function salaryRate(annual,daysPerYear,hours){return annual/Math.max(1,daysPerYear)/Math.max(1,hours)}function ticker(target,rate,start){target.textContent=money(((Date.now()-start)/3600000)*rate)}
function result(id,html){const el=$(id);if(el)el.innerHTML=html}function bind(action,fn){document.querySelectorAll('[data-action="'+action+'"]').forEach(b=>b.addEventListener('click',fn))}
function updateHomeTime(){const time=$('homeTime');if(!time)return;const now=new Date(),seconds=now.getHours()*3600+now.getMinutes()*60+now.getSeconds(),dayPercent=seconds/86400*100,weekDay=now.getDay()||7,weekPercent=((weekDay-1)+dayPercent/100)/7*100,daysInMonth=new Date(now.getFullYear(),now.getMonth()+1,0).getDate(),monthPercent=((now.getDate()-1)+dayPercent/100)/daysInMonth*100,start=new Date(now.getFullYear(),0,1),dayOfYear=Math.floor((now-start)/86400000)+1,daysInYear=new Date(now.getFullYear(),1,29).getMonth()===1?366:365,yearPercent=(dayOfYear-1+dayPercent/100)/daysInYear*100,weekNumber=Math.ceil((dayOfYear+(start.getDay()||7)-1)/7);time.textContent=now.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit',second:'2-digit'});$('homeDate').textContent=now.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'});$('homeDayPercent').textContent=Math.floor(dayPercent)+'% complete';$('homeDayBar').style.width=dayPercent+'%';$('homeWeekLabel').textContent='Day '+weekDay+' of 7';$('homeWeekBar').style.width=weekPercent+'%';$('homeMonthName').textContent=now.toLocaleDateString(undefined,{month:'long'});$('homeMonthLabel').textContent='Day '+now.getDate()+' of '+daysInMonth;$('homeMonthBar').style.width=monthPercent+'%';$('homeYearName').textContent=now.getFullYear();$('homeYearLabel').textContent='Week '+weekNumber+' · '+(daysInYear-dayOfYear)+' days left';$('homeYearBar').style.width=yearPercent+'%'}updateHomeTime();setInterval(updateHomeTime,1000);
bind('home-start',()=>{clearInterval(homeTimer);const rate=salaryRate(num('homeSalary'),260,num('homeHours'));const start=Date.now();$('homeRate').textContent=money(rate)+' per hour';ticker($('homeLive'),rate,start);homeTimer=setInterval(()=>ticker($('homeLive'),rate,start),80)});bind('home-reset',()=>{clearInterval(homeTimer);$('homeLive').textContent='$0.00'});
bind('salary-start',()=>{clearInterval(salaryTimer);const rate=salaryRate(num('annualSalary'),num('workDays'),num('hoursDay'));$('salaryHour').textContent=money(rate);$('salaryDay').textContent=money(rate*num('hoursDay'));$('salarySecond').textContent=money(rate/3600);const start=Date.now();salaryTimer=setInterval(()=>ticker($('salaryLive'),rate,start),80)});bind('salary-reset',()=>{clearInterval(salaryTimer);$('salaryLive').textContent='$0.00'});
bind('payday',()=>{const now=new Date(),end=new Date($('payDate').value+'T12:00:00');if(!end.getTime()||end<now)return result('paydayResult','Choose a future payday.');const d=days(now,end),wd=weekdays(now,end,false);result('paydayResult','<span class="big">'+d+' days</span><span class="accent">'+wd+' weekdays</span> and '+d+' sleeps until payday.');});
bind('workdays',()=>{const now=new Date(),end=new Date($('deadline').value+'T12:00:00');if(!end.getTime()||end<now)return result('workdaysResult','Choose a future deadline.');const wd=weekdays(now,end,$('includeToday').checked);result('workdaysResult','<span class="big">'+wd+' workdays</span><span class="accent">'+days(now,end)+' calendar days</span> until '+end.toLocaleDateString(undefined,{dateStyle:'long'})+'.');});
bind('afford',()=>{const price=num('itemPrice'),rate=num('takeHomePay'),h=Math.max(1,num('dailyHours'));if(price<=0||rate<=0)return result('affordResult','Enter a positive price and hourly pay.');const hours=price/rate,workdays=hours/h;result('affordResult','<span class="big">'+hours.toFixed(1)+' work hours</span>That is <span class="accent">'+workdays.toFixed(1)+' workdays</span> of your life at '+money(rate)+'/hour.');});
bind('subscription',()=>{const monthly=num('monthlyCost'),years=num('subscriptionYears'),rate=num('subHourlyPay');if(monthly<=0||years<=0||rate<=0)return result('subscriptionResult','Enter positive values.');const total=monthly*12*years,hours=total/rate;result('subscriptionResult','<span class="big">'+money(total)+'</span>Over '+years+' years, this costs <span class="accent">'+hours.toFixed(1)+' work hours</span>, or '+(hours/8).toFixed(1)+' eight-hour workdays.');});
bind('commute',()=>{const minutes=num('commuteMinutes'),daysWeek=num('commuteDays'),weeks=num('commuteWeeks'),cash=num('commuteCash'),pay=num('commutePay');const hours=minutes*daysWeek*weeks/60,totalCash=cash*daysWeek*weeks,time=hours*pay,total=totalCash+time;result('commuteResult','<span class="big">'+money(total)+' / year</span><span class="accent">'+hours.toFixed(0)+' hours</span> in transit plus '+money(totalCash)+' out of pocket. That is '+(hours/8).toFixed(1)+' eight-hour days of time.');});
bind('deadline',()=>{const fee=num('projectFee'),hours=num('projectHours'),off=num('projectDaysOff'),now=new Date(),end=new Date($('projectDeadline').value+'T12:00:00');let wd=weekdays(now,end,true)-off;if(!end.getTime()||wd<=0)return result('deadlineResult','Choose a deadline with at least one available weekday.');result('deadlineResult','<span class="big">'+(hours/wd).toFixed(1)+' hours / day</span>Across '+wd+' available workdays, target <span class="accent">'+money(fee/wd)+' revenue per day</span>. Effective project rate: '+money(fee/Math.max(1,hours))+'/hour.');});
bind('meeting-start',()=>{clearInterval(meetingTimer);const annual=num('averageSalary')*(1+num('overhead')/100),rate=annual/2080*num('attendees');$('meetingHour').textContent=money(rate);$('meetingMinute').textContent=money(rate/60);const start=Date.now();meetingTimer=setInterval(()=>ticker($('meetingLive'),rate,start),80)});bind('meeting-reset',()=>{clearInterval(meetingTimer);$('meetingLive').textContent='$0.00'});
bind('allocation',()=>{const income=num('allocIncome'),items=[['Needs',num('allocNeeds')],['Wants',num('allocWants')],['Debt',num('allocDebt')],['Savings',num('allocSavings')],['Investing',num('allocInvesting')]];if(income<=0)return result('allocationResult','Enter a positive take-home salary.');const used=items.reduce((s,x)=>s+x[1],0),left=income-used,future=num('allocSavings')+num('allocInvesting');const rows=items.map(x=>x[0]+' '+(x[1]/income*100).toFixed(1)+'%').join(' · ');result('allocationResult','<span class="big">'+money(left)+' unallocated</span>'+rows+'<br><span class="accent">Future-money rate: '+(future/income*100).toFixed(1)+'%</span> · Annual future contributions: '+money(future*12)+(left<0?'<br><b>Warning: planned spending exceeds salary by '+money(Math.abs(left))+'.</b>':''));});
bind('expense-ratio',()=>{const income=num('ratioIncome'),expenses=num('ratioHousing')+num('ratioLiving')+num('ratioDebt')+num('ratioOther');if(income<=0)return result('expenseRatioResult','Enter a positive take-home salary.');const ratio=expenses/income*100,left=income-expenses;result('expenseRatioResult','<span class="big">'+ratio.toFixed(1)+'% committed</span>Total monthly expenses: '+money(expenses)+'. <span class="accent">'+money(left)+' remains</span> before flexible spending and saving.'+(ratio>100?'<br><b>Warning: expenses exceed take-home income.</b>':''));});
bind('savings-rate',()=>{const income=num('saveIncome'),cash=num('saveCash'),invest=num('saveInvest'),employer=num('saveEmployer');if(income<=0)return result('savingsRateResult','Enter a positive take-home income.');const personal=cash+invest,total=personal+employer;result('savingsRateResult','<span class="big">'+(personal/income*100).toFixed(1)+'% personal savings rate</span>You direct '+money(personal*12)+' per year from take-home pay toward your future. Including employer contributions: <span class="accent">'+money(total*12)+' per year</span>.');});
bind('investment-ratio',()=>{const income=num('investIncome'),monthly=num('investMonthly'),current=num('investCurrent'),years=num('investYears');if(income<=0||years<=0)return result('investmentRatioResult','Enter positive income and projection years.');const principal=current+monthly*12*years;result('investmentRatioResult','<span class="big">'+(monthly/income*100).toFixed(1)+'% invested</span>Monthly contribution: '+money(monthly)+'. After '+years+' years you would have contributed <span class="accent">'+money(principal)+'</span> including your current balance, before gains or losses.');});
bind('budget-503020',()=>{const income=num('budgetIncome'),needs=num('budgetNeeds'),wants=num('budgetWants'),future=num('budgetFuture');if(income<=0)return result('budgetResult','Enter a positive take-home salary.');const target=[income*.5,income*.3,income*.2],spent=needs+wants+future,left=income-spent;result('budgetResult','<span class="big">Your current split</span>Needs '+(needs/income*100).toFixed(1)+'% · Wants '+(wants/income*100).toFixed(1)+'% · Future '+(future/income*100).toFixed(1)+'%<br><span class="accent">Reference amounts: '+money(target[0])+' / '+money(target[1])+' / '+money(target[2])+'</span><br>Unallocated: '+money(left)+(left<0?' (over budget)':''));});
bind('freelancer-allocation',()=>{const income=num('freeIncome'),parts=[['Tax reserve',num('freeTax')],['Business costs',num('freeBusiness')],['Slow-month reserve',num('freeEmergency')],['Investing',num('freeInvest')]],percent=parts.reduce((s,x)=>s+x[1],0);if(income<=0)return result('freelancerResult','Enter positive income.');if(percent>100)return result('freelancerResult','Allocation percentages total '+percent.toFixed(1)+'%. Reduce them to 100% or less.');const details=parts.map(x=>x[0]+': '+money(income*x[1]/100)).join('<br>'),pay=income*(100-percent)/100;result('freelancerResult','<span class="big">'+money(pay)+' owner pay</span>'+details+'<br><span class="accent">'+(100-percent).toFixed(1)+'% available after reserves</span>.');});
const menu=document.querySelector('.mc-menu'),nav=document.querySelector('.mc-nav nav');menu?.addEventListener('click',()=>{nav.style.display=nav.style.display==='flex'?'none':'flex'});
})();
