(()=>{'use strict';
const root=document.querySelector('[data-seo-tool]');if(!root)return;const result=root.querySelector('[data-seo-result]');let downloadable={};
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const value=id=>(document.getElementById(id)?.value||'').trim();
const show=(title,groups)=>{result.innerHTML='<strong class="mc-seo-result-title">'+esc(title)+'</strong>'+groups.map(group=>'<section class="mc-seo-status '+group.kind+'"><b>'+esc(group.label)+'</b><ul>'+group.items.map(item=>'<li>'+esc(item)+'</li>').join('')+'</ul></section>').join('')};
root.querySelectorAll('[data-seo-tab]').forEach(button=>button.addEventListener('click',()=>{const name=button.dataset.seoTab;root.querySelectorAll('[data-seo-tab]').forEach(x=>x.classList.toggle('active',x===button));root.querySelectorAll('[data-seo-panel]').forEach(panel=>panel.hidden=panel.dataset.seoPanel!==name)}));
async function fetchPage(url){const response=await fetch('/api/seo-fetch?url='+encodeURIComponent(url));const data=await response.json();if(!response.ok)throw Error(data.error||'Unable to inspect that URL.');return data}
function auditHtml(html,network={}){const doc=new DOMParser().parseFromString(html,'text/html'),critical=[],improve=[],passed=[],title=(doc.querySelector('title')?.textContent||'').trim(),description=doc.querySelector('meta[name="description"]')?.content?.trim(),canonical=doc.querySelector('link[rel="canonical"]')?.href,robots=(doc.querySelector('meta[name="robots"]')?.content||'').toLowerCase(),h1=doc.querySelectorAll('h1'),headings=[...doc.querySelectorAll('h1,h2,h3,h4,h5,h6')],images=[...doc.images],schemas=[...doc.querySelectorAll('script[type="application/ld+json"]')];
if(network.status&&network.status!==200)critical.push('HTTP status is '+network.status+', not 200.');else if(network.status===200)passed.push('Page returns HTTP 200.');
if(robots.includes('noindex'))critical.push('Meta robots contains noindex.');else passed.push('No meta noindex directive found.');
if(!title)critical.push('Title element is missing.');else{passed.push('Title found: '+title.length+' characters.');if(title.length<20||title.length>65)improve.push('Review title length ('+title.length+' characters).')}
if(!description)improve.push('Meta description is missing.');else passed.push('Meta description found: '+description.length+' characters.');
if(!canonical)improve.push('Canonical link is missing.');else passed.push('Canonical URL is present.');
if(h1.length===0)critical.push('No H1 heading found.');else if(h1.length>1)improve.push(h1.length+' H1 headings found; keep one clear primary heading.');else passed.push('One primary H1 heading found.');
let previous=0;headings.forEach(h=>{const level=Number(h.tagName[1]);if(previous&&level>previous+1)improve.push('Heading order skips from H'+previous+' to H'+level+'.');previous=level});if(headings.some(h=>!h.textContent.trim()))improve.push('One or more headings are empty.');
const missingAlt=images.filter(img=>!img.hasAttribute('alt')).length;if(missingAlt)improve.push(missingAlt+' image(s) lack an alt attribute.');else if(images.length)passed.push('All '+images.length+' images include alt attributes.');
let invalidSchema=0;schemas.forEach(s=>{try{JSON.parse(s.textContent)}catch{invalidSchema++}});if(invalidSchema)critical.push(invalidSchema+' JSON-LD block(s) contain invalid JSON.');else if(schemas.length)passed.push(schemas.length+' valid JSON-LD block(s) found.');else improve.push('No JSON-LD structured data found; add it only when appropriate.');
if(!doc.querySelector('meta[property="og:title"]'))improve.push('Open Graph title is missing.');else passed.push('Open Graph title is present.');
if(!doc.querySelector('meta[name="viewport"]'))critical.push('Mobile viewport meta tag is missing.');else passed.push('Mobile viewport tag is present.');
return {critical,improve,passed}}
async function runAudit(){try{result.textContent='Auditing…';const active=root.querySelector('[data-seo-tab].active')?.dataset.seoTab;let html,network={};if(active==='url'){const data=await fetchPage(value('auditUrl'));html=data.body;network=data}else html=value('auditHtml');if(!html)throw Error('Enter a public URL or paste page HTML.');const report=auditHtml(html,network);show('Audit complete',[{kind:'critical',label:'Critical',items:report.critical.length?report.critical:['No critical issue detected by these checks.']},{kind:'improve',label:'Improve',items:report.improve.length?report.improve:['No improvement flagged by these checks.']},{kind:'passed',label:'Passed',items:report.passed}])}catch(error){show('Audit could not run',[{kind:'critical',label:'Check input',items:[error.message]}])}}
function normalizeUrl(raw){const url=new URL(raw);if(!/^https?:$/.test(url.protocol))throw Error('Only HTTP or HTTPS URLs are allowed.');url.hash='';return url.href}
function runSitemap(){try{const active=root.querySelector('[data-seo-tab].active')?.dataset.seoTab;if(active==='generate'){const raw=value('sitemapUrls').split(/\r?\n/).map(x=>x.trim()).filter(Boolean),valid=[],invalid=[];raw.forEach(item=>{try{valid.push(normalizeUrl(item))}catch{invalid.push(item)}});const unique=[...new Set(valid)],duplicates=valid.length-unique.length;if(!unique.length)throw Error('Enter at least one valid public URL.');const xml='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+unique.map(url=>'  <url><loc>'+url.replace(/&/g,'&amp;')+'</loc></url>').join('\n')+'\n</urlset>\n';downloadable.sitemap=xml;root.querySelector('[data-seo-download="sitemap"]').disabled=false;show('Sitemap generated',[{kind:'passed',label:'Ready',items:[unique.length+' unique URL(s) included.']},{kind:'improve',label:'Review',items:[duplicates+' duplicate(s) removed.',invalid.length+' invalid URL(s) excluded.']}])}else{const xml=value('sitemapXml');if(!xml)throw Error('Paste sitemap XML.');const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror'))throw Error('The XML is not well formed.');const locs=[...doc.querySelectorAll('loc')].map(x=>x.textContent.trim()),invalid=locs.filter(x=>{try{normalizeUrl(x);return false}catch{return true}}),duplicates=locs.length-new Set(locs).size;show('Sitemap inspected',[{kind:invalid.length?'critical':'passed',label:invalid.length?'Critical':'Passed',items:[invalid.length?invalid.length+' invalid absolute URL(s).':'All locations are absolute HTTP/HTTPS URLs.']},{kind:'improve',label:'Summary',items:[locs.length+' URL location(s).',duplicates+' duplicate(s).',doc.querySelectorAll('sitemap').length+' child sitemap(s).']}])}}catch(error){show('Sitemap check failed',[{kind:'critical',label:'Check input',items:[error.message]}])}}
function parseRobots(text,agent,path){const lines=text.split(/\r?\n/),groups=[],sitemaps=[];let current=[];for(let i=0;i<lines.length;i++){const clean=lines[i].replace(/#.*$/,'').trim();if(!clean)continue;const idx=clean.indexOf(':');if(idx<0)continue;const key=clean.slice(0,idx).trim().toLowerCase(),val=clean.slice(idx+1).trim();if(key==='user-agent'){if(current.length&&current.some(x=>x.type!=='user-agent')){groups.push(current);current=[]}current.push({type:key,value:val,line:i+1})}else if(key==='allow'||key==='disallow')current.push({type:key,value:val,line:i+1});else if(key==='sitemap')sitemaps.push(val)}if(current.length)groups.push(current);const selected=groups.filter(g=>g.filter(x=>x.type==='user-agent').some(x=>x.value==='*'||x.value.toLowerCase()===agent.toLowerCase()));const rules=selected.flat().filter(x=>(x.type==='allow'||x.type==='disallow')&&x.value&&path.startsWith(x.value.replace(/\*.*$/,''))).sort((a,b)=>b.value.length-a.value.length);return {rule:rules[0],sitemaps}}
function runRobots(){try{const active=root.querySelector('[data-seo-tab].active')?.dataset.seoTab;if(active==='generate'){const domain=normalizeUrl(value('robotsDomain')),blocked=value('robotsBlocked').split(',').map(x=>x.trim()).filter(Boolean),text='User-agent: *\nAllow: /\n'+blocked.map(x=>'Disallow: '+(x.startsWith('/')?x:'/'+x)).join('\n')+'\nSitemap: '+new URL('/sitemap.xml',domain).href+'\n';downloadable.robots=text;root.querySelector('[data-seo-download="robots"]').disabled=false;show('robots.txt generated',[{kind:blocked.includes('/')?'critical':'passed',label:blocked.includes('/')?'Critical warning':'Ready',items:[blocked.includes('/')?'Disallow: / blocks the whole site.':'Generated rules allow the public site and block only listed paths.']},{kind:'improve',label:'File content',items:text.trim().split('\n')}])}else{const raw=value('robotsPath');if(!raw)throw Error('Enter a URL or path.');const path=raw.startsWith('http')?new URL(raw).pathname:raw,report=parseRobots(value('robotsRules'),value('robotsAgent'),path),blocked=report.rule?.type==='disallow';show(blocked?'Crawler is blocked':'Crawler is allowed',[{kind:blocked?'critical':'passed',label:blocked?'Blocking rule':'Result',items:[report.rule?(report.rule.type+': '+report.rule.value+' on line '+report.rule.line):'No matching blocking rule.']},{kind:'improve',label:'Sitemaps',items:report.sitemaps.length?report.sitemaps:['No sitemap directive found.']}])}}catch(error){show('Robots check failed',[{kind:'critical',label:'Check input',items:[error.message]}])}}
function verificationMarkup(platform,method,token,domain){if(method==='dns')return {host:'@',value:platform==='google'?'google-site-verification='+token:platform==='bing'?'MS='+token:'facebook-domain-verification='+token};const name=platform==='google'?'google-site-verification':platform==='bing'?'msvalidate.01':'facebook-domain-verification';return '<meta name="'+name+'" content="'+token.replace(/["<>]/g,'')+'">'}
function runVerification(){try{const platform=value('verifyPlatform'),method=value('verifyMethod'),token=value('verifyToken'),domain=value('verifyDomain').replace(/^https?:\/\//,'').split('/')[0];if(!domain||!token)throw Error('Enter a domain and the exact token supplied by the service.');const prepared=verificationMarkup(platform,method,token,domain);if(typeof prepared==='string')show('Add this tag inside the homepage <head>',[{kind:'passed',label:'HTML tag',items:[prepared]},{kind:'improve',label:'Next step',items:['Publish the page, view its source, then click Verify in '+platform+'.']}]);else show('Add this DNS TXT record',[{kind:'passed',label:'Record',items:['Type: TXT','Host: '+prepared.host,'Value: '+prepared.value,'TTL: provider default']},{kind:'improve',label:'Next step',items:['Keep the record after verification succeeds. DNS changes can take time to appear.']}])}catch(error){show('Verification helper failed',[{kind:'critical',label:'Check input',items:[error.message]}])}}
async function checkDns(){try{const domain=value('verifyDomain').replace(/^https?:\/\//,'').split('/')[0];if(!domain)throw Error('Enter a domain.');result.textContent='Checking public DNS…';const response=await fetch('/api/dns-txt?domain='+encodeURIComponent(domain)),data=await response.json();if(!response.ok)throw Error(data.error||'DNS lookup failed.');const token=value('verifyToken'),matches=data.records.filter(x=>!token||x.includes(token));show('Public DNS checked',[{kind:matches.length?'passed':'improve',label:matches.length?'Matching record found':'No matching record found',items:matches.length?matches:data.records.length?data.records:['No TXT records returned.']}])}catch(error){show('DNS check failed',[{kind:'critical',label:'Check input',items:[error.message]}])}}
function runSchema(){try{const active=root.querySelector('[data-seo-tab].active')?.dataset.seoTab;let data;if(active==='build'){const type=value('schemaType'),name=value('schemaName'),url=value('schemaUrl'),description=value('schemaDescription');if(!name||!url)throw Error('Name and canonical URL are required.');normalizeUrl(url);data={'@context':'https://schema.org','@type':type,name,url};if(description)data.description=description;if(type==='WebApplication'){data.applicationCategory='WebApplication';data.operatingSystem='Any'}if(type==='BreadcrumbList')data.itemListElement=[{'@type':'ListItem',position:1,name,url}]}else data=JSON.parse(value('schemaJson'));if(data['@context']!=='https://schema.org')throw Error('@context should be https://schema.org.');if(!data['@type'])throw Error('@type is required.');const json=JSON.stringify(data,null,2);downloadable.schema='<script type="application/ld+json">\n'+json+'\n<\/script>';root.querySelector('[data-seo-copy="schema"]').disabled=false;show('Structured data is valid JSON',[{kind:'passed',label:'Core fields',items:['@context: '+data['@context'],'@type: '+data['@type']]},{kind:'improve',label:'Confirm before publishing',items:['Properties must describe visible page content.','Test the live URL with Google Rich Results Test.']}]);result.insertAdjacentHTML('beforeend','<pre class="mc-seo-code">'+esc(json)+'</pre>')}catch(error){show('Structured data is not valid',[{kind:'critical',label:'Fix this',items:[error.message]}])}}
function runPreview(){const title=value('previewTitle')||'Example page title',url=value('previewUrl')||'https://example.com/page',description=value('previewDescription')||'A clear description of the page.',image=value('previewImage');const warnings=[];if(title.length<20||title.length>65)warnings.push('Review title length: '+title.length+' characters.');if(description.length<70||description.length>165)warnings.push('Review description length: '+description.length+' characters.');if(!image)warnings.push('Add an absolute social image URL.');const tags='<title>'+title+'</title>\n<meta name="description" content="'+description+'">\n<link rel="canonical" href="'+url+'">\n<meta property="og:title" content="'+title+'">\n<meta property="og:description" content="'+description+'">\n<meta property="og:url" content="'+url+'">\n<meta property="og:image" content="'+image+'">\n<meta name="twitter:card" content="summary_large_image">';downloadable.preview=tags;root.querySelector('[data-seo-copy="preview"]').disabled=false;document.getElementById('seoPreviews').innerHTML='<section class="mc-serp-preview"><small>'+esc(url)+'</small><h3>'+esc(title)+'</h3><p>'+esc(description)+'</p></section><section class="mc-social-preview">'+(image?'<img src="'+esc(image)+'" alt="">':'')+'<small>'+esc(new URL(url,'https://example.com').hostname)+'</small><h3>'+esc(title)+'</h3><p>'+esc(description)+'</p></section>';show('Previews updated',[{kind:warnings.length?'improve':'passed',label:warnings.length?'Review':'Ready',items:warnings.length?warnings:['Core search and social metadata is present.']}])}
root.querySelector('[data-seo-action="audit"]')?.addEventListener('click',runAudit);root.querySelector('[data-seo-action="sitemap"]')?.addEventListener('click',runSitemap);root.querySelector('[data-seo-action="robots"]')?.addEventListener('click',runRobots);root.querySelector('[data-seo-action="verification"]')?.addEventListener('click',runVerification);root.querySelector('[data-seo-action="dns-check"]')?.addEventListener('click',checkDns);root.querySelector('[data-seo-action="schema"]')?.addEventListener('click',runSchema);root.querySelector('[data-seo-action="preview"]')?.addEventListener('click',runPreview);
root.querySelectorAll('[data-seo-download]').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.seoDownload,blob=new Blob([downloadable[key]||''],{type:'text/plain'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=key==='sitemap'?'sitemap.xml':'robots.txt';link.click();URL.revokeObjectURL(link.href)}));root.querySelectorAll('[data-seo-copy]').forEach(button=>button.addEventListener('click',async()=>{const text=downloadable[button.dataset.seoCopy]||'';await navigator.clipboard.writeText(text);button.textContent='Copied'}));
})();