function tpEscape(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function toolResult(){return document.getElementById('result')}
function seedValue(){return (document.getElementById('seedKeyword')?.value||'').trim()}
function cleanSeed(){return seedValue().toLowerCase().replace(/\s+/g,' ').trim()}
function outputList(items,note=''){const result=toolResult(),clean=[...new Set(items)].filter(Boolean),signature=clean.join('|'),same=result.dataset.answerSet===signature,index=same?(Number(result.dataset.answerIndex||0)+1)%Math.max(1,clean.length):0;result.dataset.answerSet=signature;result.dataset.answerIndex=String(index);result.innerHTML=clean.length?`<pre>${tpEscape(clean[index])}</pre><small>${tpEscape(note)}${clean.length>1?' Run the tool again for another answer.':''}</small>`:'No result found.'}
function metaLength(){const description=document.getElementById('pageDesc').value||'',length=description.length;toolResult().innerHTML=`${length} characters <small>${length<120?'Could be too short':length>160?'May be too long':'Good common range'} for many search snippets.</small>`}
function serpPreview(){const title=document.getElementById('pageTitle').value||'Example Page Title',url=document.getElementById('pageUrl').value||'https://example.com/page',description=document.getElementById('pageDesc').value||'Your page description preview will appear here.';toolResult().innerHTML=`<div style="font-weight:400"><div style="color:#1a0dab;font-size:18px">${tpEscape(title)}</div><div style="color:#006621">${tpEscape(url)}</div><div>${tpEscape(description)}</div></div>`}
function readability(){const text=(document.getElementById('textInput').value||'').trim(),words=text?text.split(/\s+/):[],sentences=Math.max(1,(text.match(/[.!?]+/g)||[]).length),syllables=words.join(' ').toLowerCase().split(/\s+/).reduce((total,word)=>total+Math.max(1,(word.match(/[aeiouy]+/g)||[]).length),0),score=206.835-1.015*(words.length/sentences)-84.6*(syllables/Math.max(1,words.length));toolResult().innerHTML=`Readability score: ${score.toFixed(1)} <small>${words.length} words · ${sentences} sentences. Higher is usually easier to read.</small>`}
function slugGenerator(){const text=(document.getElementById('slugText').value||'').trim(),slug=text.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');toolResult().textContent=slug||'Please enter text.'}
function keywordResearch(){const seed=cleanSeed();if(!seed)return toolResult().textContent='Please enter a seed keyword.';outputList([`${seed} tool`,`${seed} checker`,`how to ${seed}`,`${seed} examples`,`${seed} for beginners`,`${seed} guide`,`${seed} checklist`,`${seed} step by step`],'Idea generator only. It does not show live search volume or competition data.')}
function keywordSuggestions(){const seed=cleanSeed();if(!seed)return toolResult().textContent='Please enter a seed keyword.';outputList([`What is ${seed}?`,`How does ${seed} work?`,`How to use ${seed}?`,`Why is ${seed} important?`,`Best ${seed} tools`,`${seed} examples`,`${seed} mistakes`,`${seed} alternatives`],'These are generated topic patterns, not live autocomplete data.')}
function seoTitleGenerator(){const seed=seedValue()||'Your Topic',audience=(document.getElementById('audience')?.value||'beginners').trim()||'beginners';outputList([`${seed}: Simple Guide for ${audience}`,`Best ${seed} Tips for ${audience}`,`How to Use ${seed} Step by Step`,`${seed} Checklist: What to Review Before Publishing`],'Edit the title so it accurately matches the final page.')}
function metaDescriptionGenerator(){const topic=(document.getElementById('seedKeyword')?.value||'your page').trim(),benefit=(document.getElementById('benefit')?.value||'get a clear result').trim(),ideas=[`Use this ${topic} tool to ${benefit}. Simple, fast and easy to use in your browser.`,`Try a free ${topic} helper to ${benefit}, review the result and improve your page before publishing.`];outputList(ideas.map(text=>`${text} (${text.length} characters)`),'Check the final length and make sure the description matches visible page content.')}